services:
  - type: web
    name: e-rep-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt &&  playwright install
    startCommand: hypercorn run:app --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
