"""added is processed and cofidence to comments

Revision ID: 32a4538369ab
Revises: abe975c7f804
Create Date: 2026-07-16 02:38:10.995749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a4538369ab'
down_revision = 'abe975c7f804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_processed')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
