"""added is verified user column

Revision ID: 411892e79412
Revises: d4b8e3f2a1c5
Create Date: 2026-04-01 07:41:05.975020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '411892e79412'
down_revision = 'd4b8e3f2a1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_history_page_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pages', ['page_id'], ['uuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('registered', 'subscribed', 'admin', name='user_roles'),
               nullable=False,
               existing_server_default=sa.text("'registered'::user_roles"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('registered', 'subscribed', 'admin', name='user_roles'),
               nullable=True,
               existing_server_default=sa.text("'registered'::user_roles"))
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pages_history_page_id_fkey'), 'pages', ['page_id'], ['uuid'], onupdate='CASCADE')

    # ### end Alembic commands ###
