"""adding scraping tables

Revision ID: 4798ca7d86eb
Revises: 22f006d847fb
Create Date: 2026-07-11 21:46:28.873524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798ca7d86eb'
down_revision = '22f006d847fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('posts_fetched', sa.Integer(), nullable=False),
    sa.Column('comments_inserted', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_session_status'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_username', sa.String(length=100), nullable=True),
    sa.Column('author_profile_url', sa.Text(), nullable=True),
    sa.Column('comment_timestamp', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('replies_count', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=100), nullable=True),
    sa.Column('scraping_session_id', sa.String(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scraping_session_id'], ['scraping_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'platform', 'post_id', 'comment_id', name='uq_comment_composite')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comment_post_lookup', ['page_id', 'platform', 'post_id'], unique=False)
        batch_op.create_index('ix_comment_session', ['scraping_session_id'], unique=False)

    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_history_page_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pages', ['page_id'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pages_history_page_id_fkey'), 'pages', ['page_id'], ['uuid'], onupdate='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_session')
        batch_op.drop_index('ix_comment_post_lookup')

    op.drop_table('comments')
    op.drop_table('scraping_sessions')
    # ### end Alembic commands ###
