"""added posts and posts history

Revision ID: 51c85e75eb35
Revises: 38bac017fbec
Create Date: 2026-02-12 01:22:56.855664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51c85e75eb35'
down_revision = '38bac017fbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_posts_created_at'))
        batch_op.drop_index(batch_op.f('idx_posts_extra_data'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_posts_page_platform'))
        batch_op.drop_constraint(batch_op.f('posts_page_id_platform_post_id_key'), type_='unique')
        batch_op.create_unique_constraint('uix_post_platform_page', ['page_id', 'platform', 'post_id'])

    with op.batch_alter_table('posts_history', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_posts_history_post_id'))
        batch_op.drop_index(batch_op.f('idx_posts_history_recorded_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_posts_history_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_history_post_id'), ['post_id'], unique=False)
        batch_op.alter_column('extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('uix_post_platform_page', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('posts_page_id_platform_post_id_key'), ['page_id', 'platform', 'post_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_posts_page_platform'), ['page_id', 'platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_extra_data'), ['extra_data'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_posts_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
