"""changed target_id in notes to string instead of int, changed posts to use mv

Revision ID: 5d1946c976cf
Revises: 15bc6a5f3575
Create Date: 2026-02-24 05:51:13.981724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d1946c976cf'
down_revision = '15bc6a5f3575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('posts_history_mv',
    # sa.Column('page_id', sa.UUID(), nullable=False),
    # sa.Column('platform', sa.String(length=20), nullable=False),
    # sa.Column('post_id', sa.String(length=100), nullable=False),
    # sa.Column('recorded_at', sa.DateTime(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('url', sa.Text(), nullable=True),
    # sa.Column('likes', sa.BigInteger(), nullable=True),
    # sa.Column('comments', sa.BigInteger(), nullable=True),
    # sa.Column('shares', sa.BigInteger(), nullable=True),
    # sa.Column('views', sa.BigInteger(), nullable=True),
    # sa.Column('caption', sa.Text(), nullable=True),
    # sa.Column('content_type', sa.String(length=50), nullable=True),
    # sa.Column('image_url', sa.Text(), nullable=True),
    # sa.Column('video_url', sa.Text(), nullable=True),
    # sa.Column('is_pinned', sa.Boolean(), nullable=True),
    # sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.PrimaryKeyConstraint('page_id', 'platform', 'post_id', 'recorded_at')
    # )
    # op.create_table('posts_mv',
    # sa.Column('page_id', sa.UUID(), nullable=False),
    # sa.Column('platform', sa.String(length=20), nullable=False),
    # sa.Column('post_id', sa.String(length=100), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('recorded_at', sa.DateTime(), nullable=True),
    # sa.Column('url', sa.Text(), nullable=True),
    # sa.Column('likes', sa.BigInteger(), nullable=True),
    # sa.Column('comments', sa.BigInteger(), nullable=True),
    # sa.Column('shares', sa.BigInteger(), nullable=True),
    # sa.Column('views', sa.BigInteger(), nullable=True),
    # sa.Column('caption', sa.Text(), nullable=True),
    # sa.Column('content_type', sa.String(length=50), nullable=True),
    # sa.Column('image_url', sa.Text(), nullable=True),
    # sa.Column('video_url', sa.Text(), nullable=True),
    # sa.Column('is_pinned', sa.Boolean(), nullable=True),
    # sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.PrimaryKeyConstraint('page_id', 'platform', 'post_id')
    # )
    
    op.drop_table('posts_history')
    op.drop_table('posts')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('posts',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('posts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('views', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.uuid'], name='posts_page_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    sa.UniqueConstraint('page_id', 'platform', 'post_id', name='uix_post_platform_page', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('posts_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('likes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('views', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('posts_history_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_history_pkey'))
    )
    # op.drop_table('posts_mv')
    # op.drop_table('posts_history_mv')
    # ### end Alembic commands ###
