"""added applicable to column for categories, to distinguish between influencer categories and companies categories

Revision ID: 60e26b2b35be
Revises: 80ed613e6eb8
Create Date: 2026-07-21 01:13:52.016045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e26b2b35be'
down_revision = '80ed613e6eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicable_to', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('applicable_to')

    # ### end Alembic commands ###
