"""update delete cascade

Revision ID: 80ed613e6eb8
Revises: 32a4538369ab
Create Date: 2026-07-18 11:41:37.221730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ed613e6eb8'
down_revision = '32a4538369ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_history_page_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pages', ['page_id'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pages_history_page_id_fkey'), 'pages', ['page_id'], ['uuid'])

    # ### end Alembic commands ###
