"""chpa

Revision ID: 91b948035813
Revises: ae34befa99d2
Create Date: 2025-12-25 00:29:08.460955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b948035813'
down_revision = 'ae34befa99d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.alter_column('to_scrape',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('entity_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entity_category_entity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entities', ['entity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entity_category_entity_id_fkey'), 'entities', ['entity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.alter_column('to_scrape',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
