"""empty message

Revision ID: 9f08cdf3cd09
Revises: 411892e79412
Create Date: 2026-04-19 18:45:43.420687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f08cdf3cd09'
down_revision = '411892e79412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_entity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entities', ['entity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pages_entity_id_fkey'), 'entities', ['entity_id'], ['id'])

    # ### end Alembic commands ###
