"""Fix FK to use pages.new_id instead of id

Revision ID: a21e6326f650
Revises: 
Create Date: 2025-08-22 17:37:01.654431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21e6326f650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_name_platform'), type_='unique')

    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.alter_column('new_page_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.alter_column('new_page_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('pages_name_platform'), ['name', 'platform'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
