"""added on cascade delete for entity category

Revision ID: a4c3f26a84f3
Revises: 9f08cdf3cd09
Create Date: 2026-04-19 18:50:24.115935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c3f26a84f3'
down_revision = '9f08cdf3cd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entity_category_category_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('entity_category_entity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entities', ['entity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entity_category_entity_id_fkey'), 'entities', ['entity_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('entity_category_category_id_fkey'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
