"""removed page(id)

Revision ID: a4de075c45f5
Revises: a21e6326f650
Create Date: 2025-08-22 17:51:38.693927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4de075c45f5'
down_revision = 'a21e6326f650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.alter_column('new_page_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.alter_column('new_page_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
