"""added label to comments table

Revision ID: abe975c7f804
Revises: f1a2b3c4d5e6
Create Date: 2026-07-16 02:28:04.233348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe975c7f804'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.Integer(), nullable=True))

    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pages_history_page_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pages', ['page_id'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pages_history_page_id_fkey'), 'pages', ['page_id'], ['uuid'], onupdate='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
