"""added user auth

Revision ID: ae34befa99d2
Revises: a4de075c45f5
Create Date: 2025-09-06 18:16:15.289568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae34befa99d2'
down_revision = 'a4de075c45f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('public', 'influencer', 'company', 'admin', name='user_roles'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('new_page_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pages', ['page_id'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('new_page_id_fkey'), 'pages', ['page_id'], ['uuid'], onupdate='CASCADE')

    op.drop_table('users')
    # ### end Alembic commands ###
